# Generated by Django 6.0.3 on 2026-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('no_of_guests', models.IntegerField(db_column='No_of_guests')),
                ('booking_date', models.DateTimeField(db_column='BookingDate')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(db_column='Inventory')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
